# Generated by Django 5.0.3 on 2024-04-19 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divisaData', '0002_forexdata_frequency'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='forexdata',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='forexdata',
            name='frequency',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterUniqueTogether(
            name='forexdata',
            unique_together={('symbol', 'date', 'frequency')},
        ),
    ]
