# Generated by Django 5.0.3 on 2024-04-19 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('divisaData', '0003_alter_forexdata_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='forexdata',
            unique_together={('symbol', 'date')},
        ),
        migrations.RemoveField(
            model_name='forexdata',
            name='frequency',
        ),
    ]
