# Generated by Django 5.0.3 on 2024-04-19 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('divisaData', '0005_forexdata_frequency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forexdata',
            name='frequency',
        ),
    ]
