# Generated by Django 5.0.3 on 2024-04-19 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('divisaData', '0007_forexdata_frequency'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='forexdata',
            unique_together={('symbol', 'date', 'frequency')},
        ),
    ]
