# Generated by Django 4.2.22 on 2025-06-09 00:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('divisaData', '0008_alter_forexdata_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Divisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('simbolo', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserDivisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('divisa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='divisaData.divisa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'divisa')},
            },
        ),
    ]
