# Generated by Django 4.2.22 on 2025-06-09 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divisaData', '0009_divisa_userdivisa'),
    ]

    operations = [
        migrations.AddField(
            model_name='divisa',
            name='imagen1',
            field=models.URLField(default='https://example.com/imagen1.png', max_length=500),
        ),
        migrations.AddField(
            model_name='divisa',
            name='imagen2',
            field=models.URLField(default='https://example.com/imagen2.png', max_length=500),
        ),
    ]
